DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (     ID SERIAL PRIMARY KEY,
		   	ISBN VARCHAR(32) NOT NULL UNIQUE,
                        TITLE VARCHAR(60) NOT NULL UNIQUE,
                        AUTHOR VARCHAR(60) NOT NULL,
                        PRICE DECIMAL (6,2) NOT NULL,
			QUANTITY INTEGER NOT NULL);

INSERT INTO BOOK(ISBN, TITLE, AUTHOR, PRICE, QUANTITY) VALUES('9780671820862', 'Captain America: Holocaust For Hire', 'Joseph Silva', 29.90, 20);
INSERT INTO BOOK(ISBN, TITLE, AUTHOR, PRICE, QUANTITY) VALUES('9780671820855', 'The Incredible Hulk: Cry of the Beast', 'Richard S. Meyers', 24.90, 30);
INSERT INTO BOOK(ISBN, TITLE, AUTHOR, PRICE, QUANTITY) VALUES('9780671820893', 'Iron Man: And Call My Killer...MODOK!', 'William Rotsler', 20.90, 22);
INSERT INTO BOOK(ISBN, TITLE, AUTHOR, PRICE, QUANTITY) VALUES('9780399140020', 'Spider-Man: The Venom Factor', 'Diane Duane', 18.90, 18);
