apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: kubernetes.io/basic-auth
stringData:
  user: {{ .Values.postgresql.username }}
  password: {{ .Values.postgresql.password }}
  database: {{ .Values.postgresql.database }}
