apiVersion: v1
kind: Service
metadata:
  name: warehouse-chart-postgresql
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp-postgresql
      protocol: TCP
      name: tcp-postgresql
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
