apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: kubernetes.io/basic-auth
stringData:
  user: testUser
  password: testPassword
  database: warehouse
  db-service: warehouse-chart-postgresql
