{{- if .Values.route.enabled -}}
{{- $fullName := include "warehouse-chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "warehouse-chart.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - status: "True"
      type: Admitted
    host: {{ .Values.route.host }}
    routerName: default
    wildcardPolicy: None
{{- end }}
